### ISSUE TITLE
Penambahan tabel di Admin Dataplace.jsp

### ISSUE THREAD

**Issue by kurniawan15** [kurniawan15/TravelTime-B1#10]
@rizalmdj tolong tambahlan 1 tabel untuk alamat lokasi karena di DataPlace hanya ada nama alamt saja
contoh :
nama lokasi : PVJ
Alamat : Setiabudi

**Comment by rizalmdj** [comment]
Baik Sudah saya tambahkan  tabel untuk alamat dan form imput alamat
