### ISSUE TITLE
Melakukan Literasi Pada file HTML 

### ISSUE THREAD

**Issue by FachriHammadFP** [kurniawan15/TravelTime-B1#12]
File agenda-views.html 

File ini memiliki script yang isinya menampilkan data input:
![screenshot 105](https://user-images.githubusercontent.com/31992756/31529032-d28e0820-b000-11e7-9d4d-7a36e434cdf2.png)

- title
- jadwal : 
   - start 
   - end
- link

dengan hasil upload sbb
![screenshot 106](https://user-images.githubusercontent.com/31992756/31529065-0da96e0e-b001-11e7-8468-31c7d4b591c7.png)

Yang jadi masalah, bagaimana mengambil data dan diinputkan pada variabel yang terdapat pada script html

**Comment by mohridwanhdp** [comment]
Selamat Siang Hammad

Mungkin bisa dikomunikasikan ke Team Frontend dan yang lainnya tampil data dengan kalender ditangguhkan dulu ?

**Comment by FachriHammadFP** [comment]
Oke siap kapten :)
