### ISSUE TITLE
Data kasus

### ISSUE THREAD

**Issue by kurniawan15** [kurniawan15/TravelTime-B1#17]
Hasil reviev
@muhamadaqso

**Comment by kurniawan15** [comment]
Tolong pada data kasus terdapat moda kendaraan yang tidak support (tidak memungkinkan) , jika ingin di tulis semua maka tulis semua pada setiap event, soalnya pada dabel ada yang di tulis ada yang tidak

**Comment by muhamadaqso** [comment]
okaaay
