### ISSUE TITLE
Pembuatan Skema Database

### ISSUE THREAD

**Issue by mohridwanhdp** [kurniawan15/TravelTime-B1#20]
Selamat malam

Untuk pembuatan skema database, selain pembuatan skema mohon dicobakan untuk contoh data yang ada pada tabel maupun atribut tersebut sehingga saat proses implementasi bisa lebih mudah dipahami

Terima kasih

**Comment by ajerabi** [comment]
Selamat malam 

untuk penyesuaian dengan data kasus sedang dalam proses pengerjaan dan sesegera mungkin akan di selesaikan 

Terima kasih
