### ISSUE TITLE
Pembuatan Test Case

### ISSUE THREAD

**Issue by ajerabi** [kurniawan15/TravelTime-B1#21]
Selamat malam

Untuk pembuatan Test case masih kurang spesifik dalam hal yg harus di uji dan Test case masih mengacu pada simulasi belum mengacu pada pencarian bug

Terima kasih

**Comment by rfauzan24** [comment]
Assalamualaikum wr.wb
Selamat siang, tolong minta review terkait Test Case terbaru

Terima Kasih
