### ISSUE TITLE
Review Model

### ISSUE THREAD

**Issue by fadhilshofian** [kurniawan15/TravelTime-B1#22]
1. pada class event dan lokasi, keterangan dibuat "ket"
2. pada class transportasi_terjadwal dan transportasi tidak terjadwal, kdTransportasiTerjadwal dibuat "idTransportasiTerjadwal" dan kdTransportasiTidakTerjadwal dibuat "idTransportasiTidakTerjadwal"
3. pada class traveller, kdTraveller dibuat "kd_Traveller" dan namaTraveller dibuat "nama_Traveller" (tidak sesuai dengan kaidah object oriented)

**Comment by roazadewi** [comment]
oke siap
